sources:
  wikipedia:
    indices:
      DAX:
        url: "https://en.wikipedia.org/wiki/DAX"
        table_index: 3
        columns: 
          Ticker: ["Ticker"]
          Company: ["Company"]
          Sector: ["Prime Standard Sector"]
        expected_range: [35, 45]  # DAX has 40 values, allow small deviation

      SandP500:
        url: "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
        table_index: 0
        columns: 
          Ticker: ["Symbol"]
          Company: ["Security"]
          Sector: ["GICS Sector"]
          Country: [""]
        expected_range: [500, 510] # S&P 500 has 505 values, allow small deviation

      Dow_Jones:
        url: "https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average"
        table_index: 0
        columns: 
          Ticker: ["Symbol"]
          Company: ["Company"]
          Sector: ["Industry"]
          Country: [""]
        expected_range: [28, 32] # Dow Jones has 30 values, allow small deviation

      NASDAQ-100:
        url: "https://en.wikipedia.org/wiki/NASDAQ-100"
        table_index: 3
        columns: 
          Ticker: ["Ticker"]
          Company: ["Company"]
          Sector: ["GICS Sector"]
          Country: ["Country"]
        expected_range: [98, 105] # NASDAQ-100 has 102 values, allow small deviation